version: '3.9'

services:
  web:
    build: .
    container_name: bibliotech-web
    ports:
      - "9080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
      - mailpit
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
      - SMTP_HOST=mailpit
      - SMTP_PORT=1025
    networks:
      - bibliotech-network

  db:
    image: mysql:8.0
    container_name: bibliotech-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: biblioteca
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - bibliotech-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: bibliotech-phpmyadmin
    restart: always
    ports:
      - "9081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpassword
      UPLOAD_LIMIT: 300M
    depends_on:
      - db
    networks:
      - bibliotech-network

  mailpit:
    image: axllent/mailpit
    container_name: bibliotech-mailpit
    restart: always
    ports:
      - "9082:8025"   # interfaccia web mail
      - "1025:1025"   # porta SMTP
    networks:
      - bibliotech-network

volumes:
  db_data:

networks:
  bibliotech-network:
    driver: bridge
