version: '3.8'

services:
  web:
    image: php:8.2-apache
    container_name: biblioteca_web
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
      - mailpit
    environment:
      - SMTP_HOST=mailpit
      - SMTP_PORT=1025

  db:
    image: mysql:8
    container_name: biblioteca_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: biblioteca
    ports:
      - "3306:3306"
    volumes:
      - ./sql/database.sql:/docker-entrypoint-initdb.d/database.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: biblioteca_phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db

  mailpit:
    image: axllent/mailpit
    container_name: biblioteca_mailpit
    ports:
      - "8025:8025"
      - "1025:1025"
